sudo: required

services:
- docker

os: linux

addons:
  apt:
    update: true

env:
  matrix:
  - BUILD_NAME=raspbian_crosscompiler RASPBIAN_REL=stretch
  - BUILD_NAME=raspbian_crosscompiler RASPBIAN_REL=jessie

script:
- if [ "$BUILD_NAME" = "raspbian_crosscompiler" ]; then
    sudo cross-raspbian/make-raspberry-chroot.sh -d $RASPBIAN_REL raspchroot;
  fi

