sudo: required

services:
- docker

os: linux

addons:
  apt:
    update: true

env:
  global:
  # Encrypted DOCKER_PASSWORD
  - secure: "MJb2nGcGDQtZD3SL1O9P4QxUEGSRDGDdtTkaRr3mPK5XEQhArbs86gGKfhcIq3hfmU6DEtpUumTsbB0SxZ8rvogqn7VsrPJ3tYR6ZizlMzAEwOYSbCLUXQKpk8soKhQMOjdATLtgBKogq0KMEBHfGs78dEYQ8KJE5QvgvfGTW7mUpLN5j+0qowmzbRHnoTHeJMTEHuYXXNBYFFfUnTSljlFXCmVZcIQx4zrgZN66z0YfZzOoKs7o3aPKorHHTzo8w6EkzOf5jVoDRT/qjKA8ri8ktb5A1uXl4Mm4dQ/1Of2mjitCqdk6g7QGnha0qxmLgLcjheiduZV5s5SJ4z2lLLK/DpC6kh82aWOuRNa+eLQMa5vV3foVZtw1RzA9GZsE1pnPPuneSpenYCHlRpHrDbOOgDXNx7I2OC6R/l9T1PK7+9e272TohL31s70EqrjWe7YG//f3zo7AK5Xv61t70ZDSj1IhL0/YaFP+3cOL9SdlYCkQoqukfNcagOVl0RmGZUZdprmy+RL+L83uAf0w99AjvBsJeHvnHecLsDq/9HzeWxMCodKbZglf8XFYRrhLNnYGP8uPUL3fVIwo+5c4ny52khmbc2WKGwJ/bebc8tzDc+ZXwLMsIcCow9Xbue9WVGid6aA6vJ4+fSXykTpAbUKa3/PNgCU9kNoejFunJFc="
  matrix:
  - IMAGE_NAME=raspbian IMAGE_TAG=stretch RASPBIAN_REL=$IMAGE_TAG
  - IMAGE_NAME=raspbian IMAGE_TAG=jessie RASPBIAN_REL=$IMAGE_TAG

script:
- if [ "$IMAGE_NAME" = "raspbian" ]; then
    sudo ./cross-raspbian/make-raspberry-chroot.sh -d $RASPBIAN_REL ./cross-raspbian/raspchroot &&
    docker build -t igagis/$IMAGE_NAME:$IMAGE_TAG ./cross-raspbian;
  fi

before_deploy:
- echo $DOCKER_PASSWORD | docker login --username igagis --password-stdin

deploy:
- provider: script
  skip_cleanup: true
  script: docker push igagis/$IMAGE_NAME:$IMAGE_TAG
  on:
    branch: master