sudo: required

services:
- docker

os: linux

addons:
  apt:
    update: true

env:
  matrix:
  - BUILD_NAME=raspbian_qemu RASPBIAN_REL=stretch
  - BUILD_NAME=raspbian_qemu RASPBIAN_REL=jessie

script:
- if [ "$BUILD_NAME" = "raspbian_qemu" ]; then
    sudo cross-raspbian/make-raspberry-chroot.sh -d $RASPBIAN_REL cross-raspbian/chroot &&
    docker build -t theimage ./cross-raspbian;
  fi
